name: 'Teste Node.js App'
description: 'Testet eine Node.js-Anwendung'

runs:
  using: 'composite'
  steps: 
    - name: debug sub action
      run: |
        ls -aR
    - name: call script
      run: |
        node myscript.js
      shell: bash
